### ISSUE TITLE
reduzir espaçamento superior e esquerdo do menu de categorias

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#10]
editar CSS do portal e remover o espaçamento indicado na imagem abaixo:

![photo_2017-11-10_14-30-30](https://user-images.githubusercontent.com/44172/32668503-f4128658-c624-11e7-8b75-55a3d1647be3.jpg)

**Comment by mnt-c** [comment]
Joênio segue os esboços da resolução:
```CSS
/*
  Estilo de configuração da margem lateral dos items da lista.
  Antigamente:
  padding-left: 30px;
*/

#content .link-list-block li a.icon-no-icon {
  padding-left: 0px;
}

/*
  Estilo de configuração da margem inferior do titulo da lista de items.
  Antigamente:
  margin: 0px 0px 10px 0px;
*/

#content .link-list-block .block-title {
  margin: 0px;
}
```
