### ISSUE TITLE
bug com tema de ícone awesome no tema default do noosfero

### ISSUE THREAD

**Issue by joenio** [IBICT/noosfero#9]
validar se o bug abaixo ainda ocorre e resolver em caso positivo

* https://gitlab.com/noosfero/noosfero/issues/40

após resolver s submeter ao upstream do noosfero, vamos sugerir mudar o tema de ícone padrão do noosfero para ser o awesome.

**Comment by mnt-c** [comment]
O bug relatado ainda continua, com problemas de espaçamento.

No tema do Noosfero:

![image](https://user-images.githubusercontent.com/18350825/35333741-058964bc-00f7-11e8-85e8-70f336bcff1e.png)

Aplicado ao tema da juventude:

![image](https://user-images.githubusercontent.com/18350825/35333930-b542a486-00f7-11e8-9cd3-d62dea5e55f6.png)

**Comment by mnt-c** [comment]
Procurei dentro da fonte do awesome se no caso tinha alguma alteração de espaço, porém não encontrei. Como os icones é atrelado a fonte alterei o arquivo de botões padrão do Noosfero (./public/stylesheets/buttons.scss) e consegui alguns resultados:

![image](https://user-images.githubusercontent.com/18350825/35334123-615df3e2-00f8-11e8-8658-482882424ba3.png)

```CSS
.button.with-text span, .msie .button.with-text span {
  display: inline;
  width: auto;
  /*padding-right: 4px;*/
}
a.button.with-text, a.button.with-text:visited, body.noosfero a.button.with-text, body.noosfero a.button.with-text:visited, input.button.with-text {
  background-color: #EEE;
  /*padding: 3px 2px 3px 22px;*/
  padding: 3px 2px 3px 0px;
  background-position: 3px 50%;
  border: 1px solid #AAA;
          line-height: 20px;
  height: 20px;
}
```
No caso havia um espaço de 4px no CSS, porém retirando ele sobrou ainda um espaçamento adicional de 22px que é destinado a espaço de icones. Tinha comentado os dois trechos de código e eliminou os espaços a mais, mas retira os espaços para os icones que vem em plugins.

**Comment by mnt-c** [comment]
Fiz mais alterações de CSS (comentei os valores dos espaçamentos) para melhorar a visualização da fonte que continha espaços adicionais:

1. Barra de navegação do tema principal do noosfero e barra lateral do tema do juventude:
**./public/designs/themes/base/style.scss**
```CSS
#navigation span {
  /*padding: 0px 0px 0px 30px;*/
  background-position: 5px 50%;
  background-repeat: no-repeat;
}
/* Não possui relação com o icone em si
Aplicado apenas para o tema da juventude
por melhor visualização */
#content .link-list-block {
  /*padding: 10px 0px 10px 10px;*/
}
```

2. Barra lateral de menus:
**./public/stylesheets/blocks/link-list.scss**
```CSS
/* Não possui relação com o icone em si
Aplicado apenas para o tema da juventude
por melhor visualização */
.link-list-block a {
  display: block;
  text-decoration: none;
  background-repeat: no-repeat;
  /*padding-left: 23px;*/
}
```

3. Barra lateral de menus para o tema do juventude:
**./public/designs/themes/juventude/style.css**
```CSS
/* Não possui relação com o icone em si
Aplicado apenas para o tema da juventude
por melhor visualização */
#content .link-list-block li a {
    background-color: #fff;
    border-radius:0;
    border-right: medium none;
    color: #436976;
    font-weight: normal;
    line-height: 1.4em;
    width: auto;
    font-size: 1.2em;
    padding: 0.5em;
    /*padding-left: 30px;*/
    background-position: 7px 50%;
}
/* Não possui relação com o icone em si
Aplicado apenas para o tema da juventude
por melhor visualização */
#content .profile-info-options input.button.with-text,
#content .profile-info-options a.button.with-text {
    background-color: #fff;
    border-radius: 0 0 0 0;
    display: block;
    padding-bottom: 5px;
    /*padding-left: 30px;*/
    padding-top: 5px;
    text-align: left;
}
```

4. Para resolver o caso de plugins inclui o caminho de classe até o icone que é utilizado como botão, no caso fiz apenas com o plugin comment_paragraph:

**public/stylesheets/buttons.scss**
```CSS
a.button.with-text.icon-toggle_comment_paragraph {
  padding: 3px 2px 3px 22px;
}
```

Ao final no tema do **Juventude**:
![image](https://user-images.githubusercontent.com/18350825/35403985-9838d224-01e8-11e8-9d47-5ceb6ad5453e.png)

Ao final no tema do **Noosfero**:
![image](https://user-images.githubusercontent.com/18350825/35404224-61944522-01e9-11e8-93a1-f5f566558f22.png)
